name: turn2park
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: any
  google_fonts: any
  intl: any
  shared_preferences: any
  font_awesome_flutter: any
  flutter_slidable: any
  google_nav_bar: any
  avatar_glow: any
  progress_indicators: any
  url_launcher: any
  iconly: any
  cupertino_icons: any
  flutter_screenutil: any
  flutter_map: any
  latlong2: any
  loading_animation_widget: any

  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: any

  location: any
  cached_network_image: any

  #cool_datepicker: ^1.0.3
  #animated_bottom_navigation_bar: ^0.3.2
  #flutter_snake_navigationbar: ^0.5.0
  #shimmer: any
  #qr_flutter: ^4.0.0
  #local_auth: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assects/icon.png
    - assects/driver.png
    - assects/login.jpg
    - assects/2wheel.jpg
    - assects/4wheel.png